#ifndef __GUI_CHANGEFORMAT_H__
#define __GUI_CHANGEFORMAT_H__

#include <gtk/gtk.h>
#include "../bimp-manipulations.h"

#define CHANGEFORMAT_WINDOW_W 380
#define CHANGEFORMAT_WINDOW_H 250
#define CHANGEFORMAT_WINDOW_H_EXPANDED 500

#define COMBO_FORMAT_W CHANGEFORMAT_WINDOW_W - 50
#define COMBO_FORMAT_H 30

#define LABEL_QUALITY_W 100
#define LABEL_QUALITY_H 40

#define SCALE_QUALITY_W CHANGEFORMAT_WINDOW_W - LABEL_QUALITY_W - 50
#define SCALE_QUALITY_H LABEL_QUALITY_H

#define TEXT_COMMENT_W SCALE_QUALITY_W
#define TEXT_COMMENT_H 40

#define LABEL_COMPRESSION_W 100
#define LABEL_COMPRESSION_H 30

#define COMBO_COMPRESSION_W CHANGEFORMAT_WINDOW_W - LABEL_COMPRESSION_W - 50
#define COMBO_COMPRESSION_H 25

#define SCALE_COMPRESSION_W COMBO_COMPRESSION_W
#define SCALE_COMPRESSION_H COMBO_COMPRESSION_H

#define SPIN_W 60
#define SPIN_H 25

#define FRAME_PARAMS_W CHANGEFORMAT_WINDOW_W - 100
#define FRAME_PARAMS_H CHANGEFORMAT_WINDOW_H - COMBO_FORMAT_H - 100
#define FRAME_PARAMS_H_EXPANDED CHANGEFORMAT_WINDOW_H_EXPANDED - COMBO_FORMAT_H - 100

GtkWidget* bimp_changeformat_gui_new(changeformat_settings, GtkWidget*);
void bimp_changeformat_save(changeformat_settings);

#endif
